### ISSUE TITLE
Exception on launch

### ISSUE THREAD

**Issue by dadodasyra** [romangraef/rcon-discord#4]
Exception in thread "main" java.lang.ExceptionInInitializerError
        at de.romjaki.discordrcon.Main.main(Main.java:18)
Caused by: org.json.JSONException: Expected a ',' or '}' at 66 [character 19 line 4]
        at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
        at org.json.JSONObject.<init>(JSONObject.java:263)
        at org.json.JSONTokener.nextValue(JSONTokener.java:431)
        at org.json.JSONObject.<init>(JSONObject.java:244)
        at org.json.JSONObject.<init>(JSONObject.java:357)
        at de.romjaki.discordrcon.Config.<clinit>(Config.java:32)
        ... 1 more

**Comment by Mu7aMNaD** [comment]
**Same problem.**

**Comment by lineargraph** [comment]
Ok this is old, but basically you probably have a malformed json file. it looks like a } is missing

**Comment by Mu7aMNaD** [comment]
where ?

**Comment by Mu7aMNaD** [comment]
**plz fix it or tell me how to use it.**

**Comment by lineargraph** [comment]
Do you have a sample json for me?

**Comment by lineargraph** [comment]
Well the json you are using

**Comment by Mu7aMNaD** [comment]
it worked somehow idk how, but its working now. 
Can you add like /cmd to send command to the  mc server and send the output to discord.
And Chat between mc chat and discord.

**Comment by lineargraph** [comment]
@Mu7aMNaD 
Sorry chat isn't possible / easy, especially since the chat format can vary with some servers. However a bukkit/spigot/paper/etc. plugin could do that, and those exist (however i can't think of a concrete example).
